### ISSUE TITLE
IDA freeware version

### ISSUE THREAD

**Issue by gavz** [WqyJh/qwingraph_qt5#2]
OS: Kali_x64 -> Error: /opt/idafree-7.0/qwingraph: /opt/idafree-7.0/libQt5Core.so.5: version `Qt_5.11' not found (required by /opt/idafree-7.0/qwingraph)

IDA freeware 7.0
OS: Ubuntu 14.04 -> Error: undefined symbol: _ZTI11QMainWindow

**Comment by WqyJh** [comment]
Please move the qwingraph to `/usr/local/bin` or `/usr/bin` and make sure that you have installed `libqt5core`.  
In my computer (Deepin 15.11):
```bash
apt install libqt5core5a
```

**Comment by gavz** [comment]
Thanks , it works.
